# ta-application-all
Applies all ta

In [1]:
import pandas as pd
from ta import add_all_ta_features
from ta.utils import dropna

In [2]:
df = pd.read_csv('../data/BTCUSDT-day.csv', sep=',')
df = df.drop('ignore', axis=1)
df = dropna(df)

# Add all ta features
df = add_all_ta_features(
    df, open="open", high="high", low="low", close="close", volume="volume")

/Volumes/Storage/Programming/sideprojects/env/lib/python3.9/site-packages/ta/trend.py:768: RuntimeWarning: invalid value encountered in double_scalars
  dip[i] = 100 * (self._dip[i] / self._trs[i])
/Volumes/Storage/Programming/sideprojects/env/lib/python3.9/site-packages/ta/trend.py:772: RuntimeWarning: invalid value encountered in double_scalars
  din[i] = 100 * (self._din[i] / self._trs[i])

In [3]:
df

,timestamp,open,high,low,close,volume,close_time,quote_av,trades,tb_base_av,...,momentum_wr,momentum_ao,momentum_kama,momentum_roc,momentum_ppo,momentum_ppo_signal,momentum_ppo_hist,others_dr,others_dlr,others_cr
0,2017-08-17,4261.48,4485.39,4200.74,4285.08,795.150377,1503014399999,3.454770e+06,3427,616.248541,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-65.261988,NaN,0.000000
1,2017-08-18,4285.08,4371.52,3938.77,4108.37,1199.888264,1503100799999,5.086958e+06,5233,972.868710,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.123844,-4.211287,-4.123844
2,2017-08-19,4108.37,4184.69,3850.00,4139.98,381.309763,1503187199999,1.549484e+06,2153,274.336042,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.769405,0.766460,-3.386168
3,2017-08-20,4120.98,4211.08,4032.62,4086.29,467.083022,1503273599999,1.930364e+06,2321,376.795947,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.296866,-1.305349,-4.639120
4,2017-08-21,4069.13,4119.62,3911.79,4016.00,691.743060,1503359999999,2.797232e+06,3972,557.356107,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.720142,-1.735109,-6.279463
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1356,2021-05-04,57169.39,57200.00,53046.69,53200.01,85324.625903,1620172799999,4.705402e+09,2492629,41029.688246,...,-47.972939,-292.030353,53237.299097,2.919369,-3.381598,-1.764604,-1.616994,-6.943191,-7.196003,1141.517311
1357,2021-05-05,53205.05,58069.82,52900.00,57436.11,77263.923439,1620259199999,4.327994e+09,2378119,38729.475016,...,-12.822783,-197.713618,53607.962535,12.344162,-1.524961,-1.716675,0.191715,7.962592,7.661462,1240.374275
1358,2021-05-06,57436.11,58360.00,55200.00,56393.68,70181.671908,1620345599999,3.992290e+09,2459881,34248.899643,...,-21.472621,-308.596824,53666.986941,12.679548,-0.923564,-1.558053,0.634489,-1.814938,-1.831610,1216.047308
1359,2021-05-07,56393.68,58650.00,55241.63,57314.75,74542.747829,1620431999999,4.239374e+09,2361692,36877.602566,...,-13.829800,-273.177147,53741.500998,16.809706,0.070122,-1.232418,1.302540,1.633286,1.620091,1237.542123
1360,2021-05-08,57315.49,59500.00,56900.00,58862.05,69709.906028,1620518399999,4.079554e+09,2311378,34329.699156,...,-5.075179,-197.161588,53928.977991,9.000991,0.273683,-0.931198,1.204881,2.699654,2.663856,1273.651134